name: ptk2in CC CI
on:
  push:
    branches: [ main ]
    paths:
      - 'ptk2in/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ptk2in/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make all
      id: cross_make_all
      run: |
        cd ptk2in/build
        make all
    - name: make clean
      id: cross_make_clean
      run: |
        cd ptk2in/build
        make clean
